### ISSUE TITLE
nonApproveList Not Found

### ISSUE THREAD

**Issue by svgvr8** [anyswap/anyswap-crosschain#4]
I noticed that "nonApproveList.ts" is in the .gitignore doc.

Could you please help me resolve that? Thank you

**Comment by D3athGr1p** [comment]
add file nonApproveList.ts in src/components/NonApprove/
and manually insert below code in it.

`type Item = {
  token: string
  anyToken: string
  symbol: string
  spender: string
}

export const nonApproveList: {
  [chainId: number]: Item[]
} = {}`
